### ISSUE TITLE
tests for auth system - JWT

### ISSUE THREAD

**Issue by kevinxh** [kevinxh/eTourney#11]
#6
# Basic Test cases:
## a. Register (route: _localhost/auth/register_)
- [x]  1. **POST: without email or password,** 
  
     Expected json response: error msg:**"Please enter email and password"**
- [x]  2. **POST: with invalid email form(eg. without "@")**
  
     Expected json response: error msg:**"Please fill a valid e-mail address"**
- [x]  3. **POST: with invalid password length (length<6)** 
  
     Expected json response: error msg:**"Password should be longer"**
- [x]  4. **POST: with valid email and valid password** 
  
     Expected json response: :**email: _youremail_, access_token: _a JWT_**       <----record the JWT
- [x]  5. **POST: with the same email as step 4.** 
  
     Expected json response: mongoose error msg:**email already in use.**
## b. Login (route: _localhost/auth/login_)
- [x]  6. **POST: without email or password,** 
  
     Expected json response: error msg:**"Please enter email and password"**
- [x]  7. **POST: with email that has not been registered** 
  
     Expected json response: error msg:**"Authentication failed. User not found."**
- [x]  8. **POST: with registered email but wrong password** 
  
     Expected json response: error msg:**"Authentication failed. Passwords did not match."**
- [x]  9. **POST: with registered email and the right password** 
  
     Expected json response: :**email: _youremail_, access_token: _a JWT_**     <----record the JWT
## c. test authentication routes (route: _localhost/auth/test_)
- [x]  10. **GET: without any request body and header** 
  
     Expected json response: error msg:**"Unauthorized."**
- [x]  11. **GET: with header set to Authorization = wrong JWT or random string** 
  
     Expected json response: error msg:**"Unauthorized."**
- [x]  12. **GET: with header set to Authorization = _the JWT get from step 4_** 
  
     Expected string response: **"It worked! you are:' + req.user.email."**
- [x]  13. **GET: with header set to Authorization = _the JWT get from step 8_** 
  
     Expected string response: **"It worked! you are:' + req.user.email."**

This is an example of what you will be doing if you work as a QA role in company!!
This is a learning task for you guys to familiar with the testing procedure~
I encourage everyone to do this test.
You can test HTTP requests and responses easily with a chrome plugin called [POSTman](https://www.getpostman.com/).
If you get lost, ask. :)
These are basic tests, test more with your creativity!

Thanks,

Kevin.

**Comment by kevinxh** [comment]
@lockljc @Stanley288 @Aaron931122 @Nick11111

**Comment by kevinxh** [comment]
Notes: in order to work on this specific branch that was not created by you, you need to fetch it by:

eg.:
`git fetch origin`
`git checkout server-user-authentication` <-- this will create a [tracking branch](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches#Tracking-Branches) named _server-user-authentication_ locally.

**Comment by kevinxh** [comment]
Notes: remember to install dependencies as the dependency list changed in package.json

`npm install`

it might throw error because the dependency bcrypt has other dependencies that you need to install manually on your machine. See [bcrypt dependency](https://github.com/ncb000gt/node.bcrypt.js/#dependencies) and [node-gyp installation](https://github.com/nodejs/node-gyp#installation).

**Comment by kevinxh** [comment]
Notes: remember to download file **Secret.js** on teambition. It is needed for mongoDB connection and our password hashing secret.

put secret.js in **eTourney/server/config**

**Comment by Nick11111** [comment]
At test case 5, it doesn't return "error msg:email already in use". it returns "E11000 duplicate key error index: etourney.User.$email_1 dup key: { : \"nick@sfu.ca\"

**Comment by eul721** [comment]
Iss

**Comment by eul721** [comment]
Need to include in CI/CD. Don't close it.

**Comment by eul721** [comment]
~~I've completed the automations of these tests.~~
~~You may now run `npm test` for these tests~~
You need to start the server manually atm. I'll fix it so that the server is also started when we run `npm test`
