### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by eul721** [kevinxh/eTourney#4]
Hey everybody

Can you put down your availability 

| Name | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Jack | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | X | X |
| Lock | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | 17:00~21:00 | X | X |
| Kevin | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 |
| Nick | 19:00~24:00 | 19:00~24:00 | 19:00~24:00 | 19:00~24:00 | all day | all day | 19:00~24:00 |
| Aaron | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 16:00~24:00 | all day |
| Stanley | 18:00~24:00 | 18:00~24:00 | 18:00~24:00 | 2:00~24:00 | All day | X | X |

**Comment by kevinxh** [comment]
Thanks Jack!

**Comment by eul721** [comment]
Guess it's settled now. CLosing
